[package]
name = "debroglie-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
slotmap = "1.1.1"
serde = { version="1.0.228", features = ["derive"] }
serde_derive = "1.0.228"
serde_json = "1.0.149"
ordered-float = "5.1.0"
image = { version="0.25.9", features=['serde'] }
thiserror = "2.0.18"

[profile.bench]
debug = true